### ISSUE TITLE
Таймаут вызывает утечку памяти

### ISSUE THREAD

**Issue by Lemaro86** [Bagnoles/react-app#4]
https://github.com/Bagnoles/react-app/blob/c9e644d466dcd9f6fcc4740ba6525b25d3d422a8/first-app/src/App.js#L30

Если использовать таймаут и не сбрасывать его при unmount компонента, то можно вызвать этим утечку памяти.
Поэтому лучше его удалить в случае unmount компонента. 
И использовать setInterval and clearInterval

**Comment by Bagnoles** [comment]
Сделано.
